### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by casey** [casey/degenerate#435]
## I: The Command Line is the Frontline
- [ ] For the first step, we want to make sure that we're going where the users are. I'm not sure if this is signet or testnet. We want users to be able to participate and experiment with installing new software, if possible. Also, we might want to make and receive lightning payments, so going on the network with an active lightning network would be good.
- [ ] Get a signet ord instance running
- [ ] Mine and give away rare signet ordinals
- [ ] Mint and give away signet degenerate NFTs

## II: Mainnet Ordinals
- [ ] Finish a command-line ordinal wallet that's robust and tested enough to manage ordinals on mainnet

## III: Mainnet NFTS
- [ ] Finalize the NFT spec and start minting degenerate NFTs on mainnet
